### ISSUE TITLE
Doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by putteg** [gr0sjean/zabbix-templates#17]
docker --version
Docker version 19.03.5, build 633a0ea838
python --version
Python 2.7.15+

Command:
/usr/local/bin/zabbix-docker.py list
Traceback (most recent call last):
  File "/usr/local/bin/zabbix-docker.py", line 46, in <module>
    client = docker.Client(base_url='unix://var/run/docker.sock')
AttributeError: 'module' object has no attribute 'Client'
